http:
  middlewares:
    SecHeader:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        sslRedirect: true
        sslForceHost: true
        contentSecurityPolicy: "script-src 'self'; img-src 'self'"
        referrerPolicy: "same-origin"
        featurePolicy: "vibrate 'self'; geolocation 'self'; midi 'self'; notifications 'self'; push 'self'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'self'; fullscreen 'self'"
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
    HostHeader:
      headers:
        sslHost: 'host.com'
    ApiHeader:
      headers:
        sslHost: 'api.host.com'
        customResponseHeaders:
          access-control-allow-origin: 'https://host.com'
    TransmissionHeader:
      headers:
        sslHost: 'transmission.host.com'
    H5aiHeader:
      headers:
        sslHost: 'files.host.com'
    JackettHeader:
      headers:
        sslHost: 'jackett.host.com'
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        sslRedirect: true
        sslForceHost: true
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
    ProxyHostHeader:
      headers:
        sslHost: 'traefik.host.com'
